language: csharp
solution: grayles-plus-launcher.sln
mono: none
dotnet: 2.2
dist: xenial
script:
 - dotnet restore
 - dotnet test
 - dotnet publish -c Release -r win-x64 --self-contained false
 - dotnet publish -c Release -r osx-x64 --self-contained false
 - dotnet publish -c Release -r linux-x64 --self-contained false